### PR TITLE
Modified Course folder structure.

### PR DESCRIPTION
**Pull request by muse-sisay**
Videos and subtitles are downloaded and organized in Module Folder.

### CODE REVIEW

**Comment by akikoyura** [comment]
could you update "def do_auth(user, PWD)", I can't log in and it returned this line
 "[!!] Not found login attribute
  Exit..."

**Comment by muse-sisay** [comment]
@akikoyura they might have temporarily banned your account ( or at least their is  a reCAPTCHA that you need to solve). Unfortunately you have to wait a few days it will go away.

**Comment by akikoyura** [comment]
I don't think that is the problem when I debug it returned {Response}<Response [200]>. when print profile_page_soup it returned <title>TreeHouse | Sign In </title>

**Comment by muse-sisay** [comment]
@akikoyura When you visit the website [TreeHouse](https://teamtreehouse.com/signin) is there a reCAPTCHA?

**Comment by akikoyura** [comment]
@muse-sisay  no I don't see any reCAPTCHA

**Comment by muse-sisay** [comment]
That's a bit weird, try cloning the repo and try again, I made some changes yesterday.

**Comment by akikoyura** [comment]
I downloaded new repo, then I tried to run but it also returned not found login attribute

**Comment by muse-sisay** [comment]
@akikoyura Okay I found out what the problem is. (Bare with me this is not my expertises).

The login fails because there is a missing header value, 'g-recaptcha-response-data[login]'. This header field is loaded during runtime( when the browser loads the page) using javascript. We are using requests module to make our HTTP get request, which doesn't load javascript. So we can't get that value. You can use selenium to open a browser and load the page to get that field. But it's not worth it, you can try it if you want.

I hope I make sense.
PS. I am working on something. I don't think I will release on GitHub though

**Pull request closed without merging**
